import { Listing } from "./types";

export const listings: Listing[] = [
  {
    id: "1",
    title: "Sunlit loft with harbor views",
    location: "Lisbon, Portugal",
    image: "https://picsum.photos/seed/cozy1/800/600",
    pricePerNight: 128,
    rating: 4.92,
    reviewCount: 214,
    maxGuests: 4,
    amenities: { laundry: true, petsFriendly: true, ac: true },
  },
  {
    id: "2",
    title: "Cabin tucked in the pines",
    location: "Lake Tahoe, California",
    image: "https://picsum.photos/seed/cozy2/800/600",
    pricePerNight: 245,
    rating: 4.78,
    reviewCount: 98,
    maxGuests: 6,
    amenities: { laundry: true, petsFriendly: true, ac: false },
  },
  {
    id: "3",
    title: "Minimalist studio near the canals",
    location: "Amsterdam, Netherlands",
    image: "https://picsum.photos/seed/cozy3/800/600",
    pricePerNight: 176,
    rating: 4.85,
    reviewCount: 312,
    maxGuests: 2,
    amenities: { laundry: false, petsFriendly: false, ac: true },
  },
  {
    id: "4",
    title: "Whitewashed villa above the bay",
    location: "Santorini, Greece",
    image: "https://picsum.photos/seed/cozy4/800/600",
    pricePerNight: 389,
    rating: 4.97,
    reviewCount: 156,
    maxGuests: 8,
    amenities: { laundry: true, petsFriendly: false, ac: true },
  },
  {
    id: "5",
    title: "Warm townhouse in the old quarter",
    location: "Kyoto, Japan",
    image: "https://picsum.photos/seed/cozy5/800/600",
    pricePerNight: 142,
    rating: 4.89,
    reviewCount: 187,
    maxGuests: 5,
    amenities: { laundry: true, petsFriendly: true, ac: true },
  },
  {
    id: "6",
    title: "Desert retreat with a private pool",
    location: "Joshua Tree, California",
    image: "https://picsum.photos/seed/cozy6/800/600",
    pricePerNight: 298,
    rating: 4.81,
    reviewCount: 73,
    maxGuests: 4,
    amenities: { laundry: false, petsFriendly: true, ac: true },
  },
  {
    id: "7",
    title: "Bright apartment by the Sagrada",
    location: "Barcelona, Spain",
    image: "https://picsum.photos/seed/cozy7/800/600",
    pricePerNight: 159,
    rating: 4.74,
    reviewCount: 421,
    maxGuests: 3,
    amenities: { laundry: true, petsFriendly: false, ac: true },
  },
  {
    id: "8",
    title: "Quiet chalet at the foot of the Alps",
    location: "Chamonix, France",
    image: "https://picsum.photos/seed/cozy8/800/600",
    pricePerNight: 264,
    rating: 4.93,
    reviewCount: 134,
    maxGuests: 10,
    amenities: { laundry: true, petsFriendly: true, ac: false },
  },
];
