import { Listing } from "./types";

export const listings: Listing[] = [
  {
    id: "1",
    title: "Sunlit loft with harbor views",
    location: "Lisbon, Portugal",
    image: "https://picsum.photos/seed/cozy1/800/600",
    pricePerNight: 128,
    rating: 4.92,
    reviewCount: 214,
    maxGuests: 4,
    amenities: { laundry: true, petsFriendly: true, ac: true },
  },
  {
    id: "2",
    title: "Cabin tucked in the pines",
    location: "Lake Tahoe, California",
    image: "https://picsum.photos/seed/cozy2/800/600",
    pricePerNight: 245,
    rating: 4.78,
    reviewCount: 98,
    maxGuests: 6,
    amenities: { laundry: true, petsFriendly: true, ac: false },
  },
  {
    id: "3",
    title: "Minimalist studio near the canals",
    location: "Amsterdam, Netherlands",
    image: "https://picsum.photos/seed/cozy3/800/600",
    pricePerNight: 176,
    rating: 4.85,
    reviewCount: 312,
    maxGuests: 2,
    amenities: { laundry: false, petsFriendly: false, ac: true },
  },
  {
    id: "4",
    title: "Whitewashed villa above the bay",
    location: "Santorini, Greece",
    image: "https://picsum.photos/seed/cozy4/800/600",
    pricePerNight: 389,
    rating: 4.97,
    reviewCount: 156,
    maxGuests: 8,
    amenities: { laundry: true, petsFriendly: false, ac: true },
  },
  {
    id: "5",
    title: "Warm townhouse in the old quarter",
    location: "Kyoto, Japan",
    image: "https://picsum.photos/seed/cozy5/800/600",
    pricePerNight: 142,
    rating: 4.89,
    reviewCount: 187,
    maxGuests: 5,
    amenities: { laundry: true, petsFriendly: true, ac: true },
  },
  {
    id: "6",
    title: "Desert retreat with a private pool",
    location: "Joshua Tree, California",
    image: "https://picsum.photos/seed/cozy6/800/600",
    pricePerNight: 298,
    rating: 4.81,
    reviewCount: 73,
    maxGuests: 4,
    amenities: { laundry: false, petsFriendly: true, ac: true },
  },
  {
    id: "7",
    title: "Bright apartment by the Sagrada",
    location: "Barcelona, Spain",
    image: "https://picsum.photos/seed/cozy7/800/600",
    pricePerNight: 159,
    rating: 4.74,
    reviewCount: 421,
    maxGuests: 3,
    amenities: { laundry: true, petsFriendly: false, ac: true },
  },
  {
    id: "8",
    title: "Quiet chalet at the foot of the Alps",
    location: "Chamonix, France",
    image: "https://picsum.photos/seed/cozy8/800/600",
    pricePerNight: 264,
    rating: 4.93,
    reviewCount: 134,
    maxGuests: 10,
    amenities: { laundry: true, petsFriendly: true, ac: false },
  },
  {
    id: "9",
    title: "Converted barn on a working farm",
    location: "Cotswolds, England",
    image: "https://picsum.photos/seed/cozy9/800/600",
    pricePerNight: 198,
    rating: 4.88,
    reviewCount: 142,
    maxGuests: 6,
    amenities: { laundry: true, petsFriendly: true, ac: false },
  },
  {
    id: "10",
    title: "Rooftop flat with medina views",
    location: "Marrakesh, Morocco",
    image: "https://picsum.photos/seed/cozy10/800/600",
    pricePerNight: 96,
    rating: 4.71,
    reviewCount: 268,
    maxGuests: 4,
    amenities: { laundry: false, petsFriendly: false, ac: true },
  },
  {
    id: "11",
    title: "Beach bungalow steps from the sand",
    location: "Tulum, Mexico",
    image: "https://picsum.photos/seed/cozy11/800/600",
    pricePerNight: 212,
    rating: 4.83,
    reviewCount: 331,
    maxGuests: 4,
    amenities: { laundry: false, petsFriendly: true, ac: true },
  },
  {
    id: "12",
    title: "Loft above a corner bakery",
    location: "Brooklyn, New York",
    image: "https://picsum.photos/seed/cozy12/800/600",
    pricePerNight: 231,
    rating: 4.69,
    reviewCount: 512,
    maxGuests: 3,
    amenities: { laundry: true, petsFriendly: false, ac: true },
  },
  {
    id: "13",
    title: "Fjord-side cabin with a wood sauna",
    location: "Bergen, Norway",
    image: "https://picsum.photos/seed/cozy13/800/600",
    pricePerNight: 276,
    rating: 4.95,
    reviewCount: 87,
    maxGuests: 5,
    amenities: { laundry: true, petsFriendly: true, ac: false },
  },
  {
    id: "14",
    title: "Garden cottage near the lanes",
    location: "Melbourne, Australia",
    image: "https://picsum.photos/seed/cozy14/800/600",
    pricePerNight: 167,
    rating: 4.77,
    reviewCount: 203,
    maxGuests: 4,
    amenities: { laundry: true, petsFriendly: true, ac: true },
  },
  {
    id: "15",
    title: "Skyline studio in Shibuya",
    location: "Tokyo, Japan",
    image: "https://picsum.photos/seed/cozy15/800/600",
    pricePerNight: 189,
    rating: 4.86,
    reviewCount: 476,
    maxGuests: 2,
    amenities: { laundry: true, petsFriendly: false, ac: true },
  },
  {
    id: "16",
    title: "Stone house with an olive grove",
    location: "Puglia, Italy",
    image: "https://picsum.photos/seed/cozy16/800/600",
    pricePerNight: 154,
    rating: 4.9,
    reviewCount: 119,
    maxGuests: 7,
    amenities: { laundry: true, petsFriendly: true, ac: true },
  },
  {
    id: "17",
    title: "Modern A-frame in the rainforest",
    location: "Tofino, Canada",
    image: "https://picsum.photos/seed/cozy17/800/600",
    pricePerNight: 288,
    rating: 4.94,
    reviewCount: 64,
    maxGuests: 4,
    amenities: { laundry: false, petsFriendly: true, ac: false },
  },
  {
    id: "18",
    title: "Colonial apartment on a leafy street",
    location: "Buenos Aires, Argentina",
    image: "https://picsum.photos/seed/cozy18/800/600",
    pricePerNight: 88,
    rating: 4.72,
    reviewCount: 294,
    maxGuests: 5,
    amenities: { laundry: true, petsFriendly: true, ac: true },
  },
  {
    id: "19",
    title: "Hillside casita with valley views",
    location: "Oaxaca, Mexico",
    image: "https://picsum.photos/seed/cozy19/800/600",
    pricePerNight: 114,
    rating: 4.87,
    reviewCount: 158,
    maxGuests: 3,
    amenities: { laundry: false, petsFriendly: true, ac: true },
  },
  {
    id: "20",
    title: "Riverside flat near the Charles Bridge",
    location: "Prague, Czechia",
    image: "https://picsum.photos/seed/cozy20/800/600",
    pricePerNight: 132,
    rating: 4.79,
    reviewCount: 367,
    maxGuests: 4,
    amenities: { laundry: true, petsFriendly: false, ac: false },
  },
  {
    id: "21",
    title: "Surf shack with an outdoor shower",
    location: "Ericeira, Portugal",
    image: "https://picsum.photos/seed/cozy21/800/600",
    pricePerNight: 121,
    rating: 4.76,
    reviewCount: 182,
    maxGuests: 6,
    amenities: { laundry: true, petsFriendly: true, ac: false },
  },
  {
    id: "22",
    title: "Glass cabin under the northern lights",
    location: "Rovaniemi, Finland",
    image: "https://picsum.photos/seed/cozy22/800/600",
    pricePerNight: 412,
    rating: 4.98,
    reviewCount: 96,
    maxGuests: 2,
    amenities: { laundry: false, petsFriendly: false, ac: false },
  },
  {
    id: "23",
    title: "Penthouse over the Bosphorus",
    location: "Istanbul, Türkiye",
    image: "https://picsum.photos/seed/cozy23/800/600",
    pricePerNight: 243,
    rating: 4.84,
    reviewCount: 221,
    maxGuests: 6,
    amenities: { laundry: true, petsFriendly: false, ac: true },
  },
  {
    id: "24",
    title: "Vineyard guesthouse with a long terrace",
    location: "Stellenbosch, South Africa",
    image: "https://picsum.photos/seed/cozy24/800/600",
    pricePerNight: 168,
    rating: 4.91,
    reviewCount: 108,
    maxGuests: 8,
    amenities: { laundry: true, petsFriendly: true, ac: true },
  },
  {
    id: "25",
    title: "Tiny home on a quiet meadow",
    location: "Hudson Valley, New York",
    image: "https://picsum.photos/seed/cozy25/800/600",
    pricePerNight: 149,
    rating: 4.8,
    reviewCount: 137,
    maxGuests: 2,
    amenities: { laundry: false, petsFriendly: true, ac: true },
  },
  {
    id: "26",
    title: "Artist's studio with north light",
    location: "Paris, France",
    image: "https://picsum.photos/seed/cozy26/800/600",
    pricePerNight: 207,
    rating: 4.75,
    reviewCount: 389,
    maxGuests: 2,
    amenities: { laundry: true, petsFriendly: false, ac: false },
  },
  {
    id: "27",
    title: "Overwater bungalow on the lagoon",
    location: "Bora Bora, French Polynesia",
    image: "https://picsum.photos/seed/cozy27/800/600",
    pricePerNight: 620,
    rating: 4.96,
    reviewCount: 79,
    maxGuests: 4,
    amenities: { laundry: false, petsFriendly: false, ac: true },
  },
  {
    id: "28",
    title: "Restored hanok with a courtyard",
    location: "Seoul, South Korea",
    image: "https://picsum.photos/seed/cozy28/800/600",
    pricePerNight: 173,
    rating: 4.89,
    reviewCount: 164,
    maxGuests: 5,
    amenities: { laundry: true, petsFriendly: false, ac: true },
  },
  {
    id: "29",
    title: "Lakefront cottage with a rowboat",
    location: "Muskoka, Canada",
    image: "https://picsum.photos/seed/cozy29/800/600",
    pricePerNight: 259,
    rating: 4.82,
    reviewCount: 112,
    maxGuests: 8,
    amenities: { laundry: true, petsFriendly: true, ac: false },
  },
  {
    id: "30",
    title: "Bright flat in the Latin Quarter",
    location: "Montreal, Canada",
    image: "https://picsum.photos/seed/cozy30/800/600",
    pricePerNight: 136,
    rating: 4.7,
    reviewCount: 248,
    maxGuests: 4,
    amenities: { laundry: true, petsFriendly: true, ac: true },
  },
  {
    id: "31",
    title: "Cliffside room above the Amalfi road",
    location: "Positano, Italy",
    image: "https://picsum.photos/seed/cozy31/800/600",
    pricePerNight: 344,
    rating: 4.93,
    reviewCount: 193,
    maxGuests: 3,
    amenities: { laundry: false, petsFriendly: false, ac: true },
  },
  {
    id: "32",
    title: "Loft in a converted tea warehouse",
    location: "Colombo, Sri Lanka",
    image: "https://picsum.photos/seed/cozy32/800/600",
    pricePerNight: 79,
    rating: 4.68,
    reviewCount: 141,
    maxGuests: 4,
    amenities: { laundry: true, petsFriendly: false, ac: true },
  },
  {
    id: "33",
    title: "Mountain hut on the ridge trail",
    location: "Queenstown, New Zealand",
    image: "https://picsum.photos/seed/cozy33/800/600",
    pricePerNight: 226,
    rating: 4.9,
    reviewCount: 88,
    maxGuests: 6,
    amenities: { laundry: true, petsFriendly: true, ac: false },
  },
  {
    id: "34",
    title: "Sunny apartment near the Prado",
    location: "Madrid, Spain",
    image: "https://picsum.photos/seed/cozy34/800/600",
    pricePerNight: 145,
    rating: 4.73,
    reviewCount: 405,
    maxGuests: 5,
    amenities: { laundry: true, petsFriendly: true, ac: true },
  },
  {
    id: "35",
    title: "Houseboat on a quiet canal",
    location: "Utrecht, Netherlands",
    image: "https://picsum.photos/seed/cozy35/800/600",
    pricePerNight: 183,
    rating: 4.86,
    reviewCount: 127,
    maxGuests: 3,
    amenities: { laundry: false, petsFriendly: true, ac: false },
  },
  {
    id: "36",
    title: "Adobe casa with a rooftop firepit",
    location: "Santa Fe, New Mexico",
    image: "https://picsum.photos/seed/cozy36/800/600",
    pricePerNight: 211,
    rating: 4.85,
    reviewCount: 154,
    maxGuests: 6,
    amenities: { laundry: true, petsFriendly: true, ac: true },
  },
  {
    id: "37",
    title: "Treehouse above a coffee farm",
    location: "Monteverde, Costa Rica",
    image: "https://picsum.photos/seed/cozy37/800/600",
    pricePerNight: 163,
    rating: 4.92,
    reviewCount: 102,
    maxGuests: 4,
    amenities: { laundry: false, petsFriendly: false, ac: false },
  },
  {
    id: "38",
    title: "Georgian flat on a cobbled close",
    location: "Edinburgh, Scotland",
    image: "https://picsum.photos/seed/cozy38/800/600",
    pricePerNight: 192,
    rating: 4.81,
    reviewCount: 236,
    maxGuests: 5,
    amenities: { laundry: true, petsFriendly: false, ac: false },
  },
  {
    id: "39",
    title: "Courtyard riad with a plunge pool",
    location: "Fez, Morocco",
    image: "https://picsum.photos/seed/cozy39/800/600",
    pricePerNight: 118,
    rating: 4.88,
    reviewCount: 173,
    maxGuests: 8,
    amenities: { laundry: true, petsFriendly: false, ac: true },
  },
  {
    id: "40",
    title: "Alpine studio by the gondola",
    location: "Zermatt, Switzerland",
    image: "https://picsum.photos/seed/cozy40/800/600",
    pricePerNight: 302,
    rating: 4.94,
    reviewCount: 148,
    maxGuests: 2,
    amenities: { laundry: true, petsFriendly: false, ac: false },
  },
  {
    id: "41",
    title: "Beach house with a shaded deck",
    location: "Byron Bay, Australia",
    image: "https://picsum.photos/seed/cozy41/800/600",
    pricePerNight: 274,
    rating: 4.79,
    reviewCount: 217,
    maxGuests: 7,
    amenities: { laundry: true, petsFriendly: true, ac: true },
  },
  {
    id: "42",
    title: "Warehouse loft in the arts district",
    location: "Berlin, Germany",
    image: "https://picsum.photos/seed/cozy42/800/600",
    pricePerNight: 138,
    rating: 4.71,
    reviewCount: 358,
    maxGuests: 4,
    amenities: { laundry: true, petsFriendly: true, ac: false },
  },
  {
    id: "43",
    title: "Stilt house over the mangroves",
    location: "Koh Lanta, Thailand",
    image: "https://picsum.photos/seed/cozy43/800/600",
    pricePerNight: 92,
    rating: 4.83,
    reviewCount: 196,
    maxGuests: 4,
    amenities: { laundry: false, petsFriendly: true, ac: true },
  },
  {
    id: "44",
    title: "Cottage with a walled rose garden",
    location: "Galway, Ireland",
    image: "https://picsum.photos/seed/cozy44/800/600",
    pricePerNight: 156,
    rating: 4.87,
    reviewCount: 129,
    maxGuests: 6,
    amenities: { laundry: true, petsFriendly: true, ac: false },
  },
  {
    id: "45",
    title: "Loft with a view of the Duomo",
    location: "Florence, Italy",
    image: "https://picsum.photos/seed/cozy45/800/600",
    pricePerNight: 229,
    rating: 4.9,
    reviewCount: 284,
    maxGuests: 3,
    amenities: { laundry: false, petsFriendly: false, ac: true },
  },
  {
    id: "46",
    title: "Ranch house on the high plains",
    location: "Bozeman, Montana",
    image: "https://picsum.photos/seed/cozy46/800/600",
    pricePerNight: 254,
    rating: 4.76,
    reviewCount: 91,
    maxGuests: 10,
    amenities: { laundry: true, petsFriendly: true, ac: true },
  },
  {
    id: "47",
    title: "Sea-view apartment in the old town",
    location: "Dubrovnik, Croatia",
    image: "https://picsum.photos/seed/cozy47/800/600",
    pricePerNight: 187,
    rating: 4.84,
    reviewCount: 262,
    maxGuests: 5,
    amenities: { laundry: true, petsFriendly: false, ac: true },
  },
  {
    id: "48",
    title: "Windmill cottage on the polder",
    location: "Zaanse Schans, Netherlands",
    image: "https://picsum.photos/seed/cozy48/800/600",
    pricePerNight: 205,
    rating: 4.89,
    reviewCount: 76,
    maxGuests: 4,
    amenities: { laundry: false, petsFriendly: true, ac: false },
  },
  {
    id: "49",
    title: "Terraced flat above the harbour",
    location: "Reykjavík, Iceland",
    image: "https://picsum.photos/seed/cozy49/800/600",
    pricePerNight: 236,
    rating: 4.82,
    reviewCount: 145,
    maxGuests: 6,
    amenities: { laundry: true, petsFriendly: false, ac: false },
  },
  {
    id: "50",
    title: "Poolside villa in the rice fields",
    location: "Ubud, Indonesia",
    image: "https://picsum.photos/seed/cozy50/800/600",
    pricePerNight: 134,
    rating: 4.95,
    reviewCount: 308,
    maxGuests: 8,
    amenities: { laundry: true, petsFriendly: false, ac: true },
  },
];
